### ISSUE TITLE
ReferenceError: module is not defined

### ISSUE THREAD

**Issue by M3dard** [gr2m/contenteditable-autocomplete#10]
When I used bower for download new version I cant simply run that cause exception "ReferenceError: module is not defined". 
I tried to make build but resultant dist js file is corrupt. Do i need Webpack for build?

I think it's nonsense need to make build for single usage of this little library..

**Comment by gr2m** [comment]
see https://github.com/gr2m/contenteditable-autocomplete/issues/9
