### ISSUE TITLE
Can not delete old versions!!!!!

### ISSUE THREAD

**Issue by M3dard** [gr2m/contenteditable-autocomplete#9]
Man I used your older version via bower and one day I tried make bower install and it told me it can find selected version of contenteditable-autocomplete....

**Comment by gr2m** [comment]
I’m sorry for that, I don’t know what exactly happened. Bower was too much pain in the past and I’m not using it myself. As many other projects do, I migrated to npm. You can install it with `npm install --save contenteditable-autocomplete`.

Does that work for you?
